version: 0.0.0.{build}-ci
image: Visual Studio 2017
init:
- ps: >-
    if ($env:appveyor_repo_tag -eq 'true') {
        $tag = $env:appveyor_repo_tag_name
        Update-AppveyorBuild -Version "$tag"
    }
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
build_script:
- ps: dotnet build
- ps: dotnet test
- ps: dotnet pack
artifacts:
- path: '**/*.nupkg'